import type { Metadata } from "next";
import { Fira_Code, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const firaCode = Fira_Code({
    variable: "--font-fira-code",
    subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export const metadata: Metadata = {
    metadataBase: new URL("https://your-domain.com"),

    title: {
        default: "Muchamad Afif Buchori | Frontend Developer & IT Support",
        template: "%s | Muchamad Afif Buchori",
    },

    description:
        "Portfolio of Muchamad Afif Buchori, a Frontend Developer and IT Support with over 3 years of experience building modern web applications using React, Next.js, TypeScript, Laravel, and providing IT support services.",

    keywords: [
        "Muchamad Afif Buchori",
        "Afif Buchori",
        "Frontend Developer",
        "Frontend Engineer",
        "React Developer",
        "Next.js Developer",
        "JavaScript Developer",
        "TypeScript Developer",
        "Laravel",
        "IT Support",
        "Portfolio",
        "Software Engineer",
        "Web Developer",
        "Bali",
        "Indonesia",
    ],

    authors: [
        {
            name: "Muchamad Afif Buchori",
        },
    ],

    creator: "Muchamad Afif Buchori",

    publisher: "Muchamad Afif Buchori",

    robots: {
        index: true,
        follow: true,
    },

    alternates: {
        canonical: "https://your-domain.com",
    },

    openGraph: {
        title: "Muchamad Afif Buchori | Frontend Developer & IT Support",
        description:
            "Frontend Developer with experience in React, Next.js, TypeScript, Laravel, and IT Support. Explore my portfolio, projects, and professional experience.",
        url: "https://your-domain.com",
        siteName: "Muchamad Afif Buchori Portfolio",
        locale: "en_US",
        type: "website",
        images: [
            {
                url: "/images/profile.jpg",
                width: 1200,
                height: 630,
                alt: "Muchamad Afif Buchori",
            },
        ],
    },

    twitter: {
        card: "summary_large_image",
        title: "Muchamad Afif Buchori | Frontend Developer & IT Support",
        description: "Frontend Developer specializing in React, Next.js, TypeScript, Laravel, and IT Support.",
        images: ["/images/profile.jpg"],
    },

    category: "technology",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={`${firaCode.variable} h-full antialiased dark`}>
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
        // <html lang="en" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
        //     <body className="min-h-full flex flex-col">{children}</body>
        // </html>
    );
}
